### PR TITLE
Maintain compatibility with PSR

### LINKED ISSUE #63: PSR7 getHeader in OpenSwoole\Core\Psr\ServerRequest should return array of string
version: openswoole/core: "22.1.2"

getHeader in OpenSwoole\Core\Psr\ServerRequest should return `array of string` instead of `string `

code:
```php
$server->on("request", function (OpenSwoole\Http\Request $request, OpenSwoole\Http\Response $response) {

    $psr_request = \OpenSwoole\Core\Psr\ServerRequest::from($request);
    var_dump($psr_request->getHeader("NotExistsHeader"));
    var_dump($psr_request->getHeader("Accept"));

    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");

});
```

vardump
```
array(0) {
}
string(135) "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
```

$psr_request->getHeader("Accept");  // should return ["text/html","application/xhtml+xml","application/xml;q=0.9","image/avif","image/webp","image/apng","*/*;q=0.8","application/signed-exchange;v=b3;q=0.7"]

### LINKED ISSUE #72: Psr Message definition not respected to read multiple header values
The MessageInterface states that

- `getHeaderLine` will return a string
- `getHeader` will return an array

The Psr implementation in OpenSwoole always returns a string, making it incompatible with 3rd party libraries expecting Psr format.

Workaround: add and extra middleware to wrap the request.

### PR DESCRIPTION
**Pull request by alijvhr**
Make "Message.php" declarations compatible with "Psr\Http\Message\MessageInterface" to avoid fatal error in swoole:latest docker image.
This PR Resolves #63, resolves #72.

### CODE REVIEW

**Review by lotharthesavior — CHANGES_REQUESTED** [review]
Thank you so much for your contribution. I left some comments, let me know your thoughts.

**Review by lotharthesavior — APPROVED** [review]
Looks good to me! Thanks for the contribution!

**Comment by sergeliatko** [comment]
Hi guys, any chance to get this merged? Thank you.

**Comment by alijvhr** [comment]
@lotharthesavior is there any chance to update the packagist version based on this PR to install with composer?

**Comment by lotharthesavior** [comment]
I mentioned your case to the main maintainer of that source code in the Slack community. I am still waiting to receive an answer. @alijvhr

**Comment by lotharthesavior** [comment]
Hi @alijvhr , I just noticed that these changes merged here got synced with the main package and are available there. Thank you for your contribution.

**Pull request merged**
